---
- name: NodeJS Repository
  copy: src=nodesource-el7.repo dest=/etc/yum.repos.d/

- name: NodeJS GPG Key
  copy: src=NODESOURCE-GPG-SIGNING-KEY-EL dest=/etc/pki/rpm-gpg

#- name: EPEL Repository
#  copy: src=epel.repo dest=/etc/yum.repos.d/

#- name: EPEL GPG Key
#  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

