---
  - name: Install Nginx
    yum: name=nginx state=present

  - name: Create nginx config file
    template: src=nginx.conf dest=/etc/nginx/nginx.conf
    notify: restart nginx

  - name: http service
    service: name=nginx state=started enabled=yes

  - name: Configure SELinux to httpd
    seboolean: name=httpd_can_network_connect state=true persistent=yes
    when: ansible_selinux.status == "enabled"
