---
  - name: Install Nginx
    yum: name=nginx state=present

  - name: Create nginx config file
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf

  - name: Create directory for SSL
    file: path=/etc/nginx/ssl state=directory

  - name: Create SSL Certification files
    copy: src=server.crt dest=/etc/nginx/ssl/server.crt owner=root mode=0600

  - name: Create SSL Certification files
    copy: src=server.key dest=/etc/nginx/ssl/server.key owner=root mode=0600
    notify: restart nginx

  - name: http service
    service: name=nginx state=started enabled=yes

  - name: Configure SELinux to httpd
    seboolean: name=httpd_can_network_connect state=true persistent=yes
    when: ansible_selinux.status == "enabled"
