---
- name: Instalacao e configuração das roles common, repos, node,  nginx e messages
  hosts: localhost
  connection: local

  roles:
    - common
    - repos
    - nodeJs
    - nginx
    - messages
