---
- name: Inicializacao da instalacao e configuração das roles common; repos; node; nginx e info.
  hosts: localhost
  connection: local

  roles:
    - common
    - repos
    - nodeJs
    - nginx
    - info
