---
  - name: Install NodeJS
    yum: name=nodejs state=present

  - name: Create directory for nodeJS Linx App
    file: path=/srv/www/nodejs state=directory

  - name: install NPM
    shell: npm i
    args:
      chdir: /srv/www/nodejs

  - name: Install Express
    npm:
      name: express
    args:
      path: /srv/www/nodejs
      global: no

  - name: Install PM2
    npm:
      name: pm2
      global: yes

  - name: Create app config file
    copy: src=app.js dest=/srv/www/nodejs/app.js

  - name: Start App Linx
    shell: pm2 -f start app.js -n linx --watch --watch-delay 4
    args:
      chdir: /srv/www/nodejs

  - name: Save status App Linx
    shell: pm2 save --force 
    args:
      chdir: /srv/www/nodejs

  - name: Systemd App Linx
    shell: pm2 startup --service-name linx 
    args:
      chdir: /srv/www/nodejs

  - name: Create linx monit file
    copy: src=linx.mon dest=/etc/monit.d/linx.conf
    notify: restart monit

  - name: Service Linx pm2 Cluster
    service: name=linx.service state=started enabled=yes

