---
  - name: Install NodeJS
    yum: name=nodejs state=present

  - name: Create directory for nodeJS Linx App
    file: path=/srv/www/nodejs state=directory

  - name: install NPM
    shell: npm i
    args:
      chdir: /srv/www/nodejs

  - name: Install Express
    npm:
      name: express
      global: yes

  - name: Install PM2
    npm:
      name: pm2
      global: yes

#  - name: Copy TLS key
#    copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600

#  - name: Copy TLS certificate
#    copy: src=files/nginx.crt dest={{ cert_file }} owner=root mode=0600

#  - name: Copy Nginx config file
#    template: src=templates/nginx.conf.j2 dest={{ conf_file }}


  - name: Create app cluster config file
    copy: src=cluster.js dest=/srv/www/nodejs/cluster.js

  - name: Create app node config file
    copy: src=node.js dest=/srv/www/nodejs/node.js

  - name: Start App Linx
    shell: pm2 -f start cluster.js
    args:
      chdir: /srv/www/nodejs

#  - name: Start App Linx
#    shell: pm2 startup cluster.js
#    args:
#      chdir: /srv/www/nodejs

  - name: Service PM2 Cluster
    service: name=pm2-root.service state=started enabled=yes

