---
- name: Node JS Repository
  yum_repository:
    name: Node.js Packages for Enterprise Linux 7 - $basearch
    description: Node JS YUM repo
    file: node.repo
    baseurl: https://rpm.nodesource.com/pub_12.x/el/7/$basearch
    failovermethod: priority
    enabled: yes
    gpgcheck: yes
    gpgkey: file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

- name: Node JS Repository source
  yum_repository:
    name: Node.js for Enterprise Linux 7 - $basearch - Source
    description: Node JS YUM repo
    file: node.repo
    baseurl: https://rpm.nodesource.com/pub_12.x/el/7/SRPMS
    failovermethod: priority
    enabled: no
    gpgcheck: 1
    gpgkey: file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

